# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa3e9e0cc476ce49b234b7531b5354d58bc2956eb92bc4b97de054b4858874144e5930a064a4c888d758cfc7705a4754bb0eccbace45c91ea420f425b21ee2d

test:
  secret_key_base: 036affe2009cd806ec74b25c15ee9e6834fe1d7ef54c0ca2e82df3953944bd21d9b3f2e40267e03500c5d4b34b65932bac09593a08f8e36655f8f9f3bba26287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
